### ISSUE TITLE
time.time_ns() requires python>=3.7

### ISSUE THREAD

**Issue by codebywinston** [einzigartigerName/i3-workspace-swap#1]
[setup.py](https://github.com/einzigartigerName/i3-workspace-swap/blob/6bd00fbb25eceeba9aa18674210adb00db84ddf4/setup.py#L29) has `python_requires='>=3.6'`, but the file [i3-workspace-swap](https://github.com/einzigartigerName/i3-workspace-swap/blob/6bd00fbb25eceeba9aa18674210adb00db84ddf4/i3-workspace-swap#L59) uses `time.time_ns()`, which [requires python version 3.7 or higher](https://docs.python.org/3/library/time.html#time.time_ns).

**Comment by nelsongillo** [comment]
Fixed, thank you for pointing it out to me
